--step 1
CREATE TABLE orders (
    OrderID VARCHAR(20),
    Date DATE,
    CustomerID VARCHAR(20),
    Product VARCHAR(100),
    Quantity INT,
    UnitPrice DECIMAL(10,2),
    ShippingAddress TEXT,
    PaymentMethod VARCHAR(50),
    OrderStatus VARCHAR(50),
    TrackingNumber VARCHAR(50),
    ItemsInCart INT,
    CouponCode VARCHAR(30),
    ReferralSource VARCHAR(50),
    TotalPrice DECIMAL(10,2)
);

--TASK 6: Sales Trend Analysis Using Aggregations
--Business Problem

--An online retail company wants to understand its monthly sales performance. The management needs to identify monthly revenue trends and order volume to make better business decisions regarding inventory planning, marketing campaigns, and seasonal demand forecasting.

--Business Objective
--Analyze monthly revenue.
--Analyze monthly order volume.
--Identify sales trends over time.
--Find top-performing months.
--Support business decision-making using SQL aggregations.

-- ============================================================
-- TASK 6 : Sales Trend Analysis Using Aggregations
-- Business Problem:
-- The company wants to analyze monthly revenue and order volume
-- to understand sales trends and improve business decisions.


-
-- Query 1 : Display first 10 records
-- Purpose : Verify imported dataset


SELECT *
FROM orders
LIMIT 10;

-- Query 2 : Monthly Revenue and Order Volume
-- Purpose : Calculate revenue and number of orders every month
SELECT
    EXTRACT(YEAR FROM date) AS Sales_Year,
    EXTRACT(MONTH FROM date) AS Sales_Month,
    COUNT(DISTINCT orderid) AS Order_Volume,
    SUM(totalprice) AS Total_Revenue
FROM orders
GROUP BY
    EXTRACT(YEAR FROM date),
    EXTRACT(MONTH FROM date)
ORDER BY
    Sales_Year,
    Sales_Month;


-- Query 3: Revenue Analysis for 2024

SELECT
    EXTRACT(MONTH FROM date) AS month,
    COUNT(DISTINCT orderid) AS total_orders,
    SUM(totalprice) AS total_revenue
FROM orders
WHERE EXTRACT(YEAR FROM date) = 2024
GROUP BY
    EXTRACT(MONTH FROM date)
ORDER BY
    month;

	--Query 4: Top 3 Months by Revenue

	SELECT
    EXTRACT(YEAR FROM date) AS sales_year,
    EXTRACT(MONTH FROM date) AS sales_month,
    SUM(totalprice) AS total_revenue
FROM orders
GROUP BY
    EXTRACT(YEAR FROM date),
    EXTRACT(MONTH FROM date)
ORDER BY
    total_revenue DESC
LIMIT 3;

-- Query 5: Average Revenue Per Order
-- Business Problem:
-- Find the average revenue generated from each order.

SELECT
    ROUND(AVG(totalprice), 2) AS average_order_value
FROM orders;


-- Query 6: Total Business Revenue
-- Business Problem:
-- Calculate the total revenue generated by all orders.


SELECT
    SUM(totalprice) AS total_revenue
FROM orders;

-- Query 7: Total Orders
-- Business Problem:
-- Count the total number of unique orders.


SELECT
    COUNT(DISTINCT orderid) AS total_orders
FROM orders;

-- Query 8: Top 5 Products by Revenue
-- Business Problem:
-- Identify the products generating the highest revenue.


SELECT
    product,
    SUM(totalprice) AS total_revenue
FROM orders
GROUP BY product
ORDER BY total_revenue DESC
LIMIT 5;

-- ============================================================
-- Business Insights
-- ============================================================

-- 1. Monthly revenue helps identify seasonal sales trends.
-- 2. Order volume shows customer purchasing behavior.
-- 3. Top revenue months help plan future marketing campaigns.
-- 4. Product-wise revenue highlights best-selling products.
-- 5. Average order value helps measure customer spending patterns.

